name: Opt2q
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: opt2q-conda-env.yml
        activate-environment: opt2q
        python-version: 3.6
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda install -n opt2q -c alubbock pysb
        conda info
        conda list
    - name: Run Tests
      run: |
        $CONDA/envs/opt2q/bin/python -m unittest discover -s test -p "test_*.py"